-- Flashcard decks for every supported language (previously only es/fr/ru),
-- plus two new categories.
-- For language = 'en' the reference word is Spanish, matching the Learn path.

-- "Hello" and "Good morning" were both "Bonjour" in French, so the two cards
-- had the same answer.
UPDATE category_words SET translation = 'Salut'
WHERE category_id = 1 AND language = 'fr' AND word = 'Hello' AND translation = 'Bonjour';

INSERT IGNORE INTO categories (id, name, icon) VALUES
  (3, 'Animals', '🐾'),
  (4, 'Clothes', '👕');

INSERT INTO category_words (category_id, language, word, translation) VALUES
  (1, 'de', 'Hello', 'Hallo'),
  (1, 'de', 'Goodbye', 'Auf Wiedersehen'),
  (1, 'de', 'Good morning', 'Guten Morgen'),
  (1, 'de', 'Thank you', 'Danke'),
  (1, 'de', 'Please', 'Bitte'),
  (1, 'de', 'Sorry', 'Entschuldigung'),
  (2, 'de', 'Bread', 'Brot'),
  (2, 'de', 'Water', 'Wasser'),
  (2, 'de', 'Apple', 'Apfel'),
  (2, 'de', 'Chicken', 'Hähnchen'),
  (2, 'de', 'Rice', 'Reis'),
  (2, 'de', 'Coffee', 'Kaffee'),
  (1, 'it', 'Hello', 'Ciao'),
  (1, 'it', 'Goodbye', 'Arrivederci'),
  (1, 'it', 'Good morning', 'Buongiorno'),
  (1, 'it', 'Thank you', 'Grazie'),
  (1, 'it', 'Please', 'Per favore'),
  (1, 'it', 'Sorry', 'Scusa'),
  (2, 'it', 'Bread', 'Pane'),
  (2, 'it', 'Water', 'Acqua'),
  (2, 'it', 'Apple', 'Mela'),
  (2, 'it', 'Chicken', 'Pollo'),
  (2, 'it', 'Rice', 'Riso'),
  (2, 'it', 'Coffee', 'Caffè'),
  (1, 'pt', 'Hello', 'Olá'),
  (1, 'pt', 'Goodbye', 'Tchau'),
  (1, 'pt', 'Good morning', 'Bom dia'),
  (1, 'pt', 'Thank you', 'Obrigado'),
  (1, 'pt', 'Please', 'Por favor'),
  (1, 'pt', 'Sorry', 'Desculpa'),
  (2, 'pt', 'Bread', 'Pão'),
  (2, 'pt', 'Water', 'Água'),
  (2, 'pt', 'Apple', 'Maçã'),
  (2, 'pt', 'Chicken', 'Frango'),
  (2, 'pt', 'Rice', 'Arroz'),
  (2, 'pt', 'Coffee', 'Café'),
  (1, 'zh', 'Hello', '你好'),
  (1, 'zh', 'Goodbye', '再见'),
  (1, 'zh', 'Good morning', '早上好'),
  (1, 'zh', 'Thank you', '谢谢'),
  (1, 'zh', 'Please', '请'),
  (1, 'zh', 'Sorry', '对不起'),
  (2, 'zh', 'Bread', '面包'),
  (2, 'zh', 'Water', '水'),
  (2, 'zh', 'Apple', '苹果'),
  (2, 'zh', 'Chicken', '鸡肉'),
  (2, 'zh', 'Rice', '米饭'),
  (2, 'zh', 'Coffee', '咖啡'),
  (1, 'en', 'Hola', 'Hello'),
  (1, 'en', 'Adiós', 'Goodbye'),
  (1, 'en', 'Buenos días', 'Good morning'),
  (1, 'en', 'Gracias', 'Thank you'),
  (1, 'en', 'Por favor', 'Please'),
  (1, 'en', 'Lo siento', 'Sorry'),
  (2, 'en', 'Pan', 'Bread'),
  (2, 'en', 'Agua', 'Water'),
  (2, 'en', 'Manzana', 'Apple'),
  (2, 'en', 'Pollo', 'Chicken'),
  (2, 'en', 'Arroz', 'Rice'),
  (2, 'en', 'Café', 'Coffee'),
  (3, 'es', 'Dog', 'Perro'),
  (3, 'es', 'Cat', 'Gato'),
  (3, 'es', 'Bird', 'Pájaro'),
  (3, 'es', 'Fish', 'Pez'),
  (3, 'es', 'Horse', 'Caballo'),
  (3, 'es', 'Cow', 'Vaca'),
  (3, 'fr', 'Dog', 'Chien'),
  (3, 'fr', 'Cat', 'Chat'),
  (3, 'fr', 'Bird', 'Oiseau'),
  (3, 'fr', 'Fish', 'Poisson'),
  (3, 'fr', 'Horse', 'Cheval'),
  (3, 'fr', 'Cow', 'Vache'),
  (3, 'de', 'Dog', 'Hund'),
  (3, 'de', 'Cat', 'Katze'),
  (3, 'de', 'Bird', 'Vogel'),
  (3, 'de', 'Fish', 'Fisch'),
  (3, 'de', 'Horse', 'Pferd'),
  (3, 'de', 'Cow', 'Kuh'),
  (3, 'it', 'Dog', 'Cane'),
  (3, 'it', 'Cat', 'Gatto'),
  (3, 'it', 'Bird', 'Uccello'),
  (3, 'it', 'Fish', 'Pesce'),
  (3, 'it', 'Horse', 'Cavallo'),
  (3, 'it', 'Cow', 'Mucca'),
  (3, 'pt', 'Dog', 'Cachorro'),
  (3, 'pt', 'Cat', 'Gato'),
  (3, 'pt', 'Bird', 'Pássaro'),
  (3, 'pt', 'Fish', 'Peixe'),
  (3, 'pt', 'Horse', 'Cavalo'),
  (3, 'pt', 'Cow', 'Vaca'),
  (3, 'ru', 'Dog', 'Собака'),
  (3, 'ru', 'Cat', 'Кошка'),
  (3, 'ru', 'Bird', 'Птица'),
  (3, 'ru', 'Fish', 'Рыба'),
  (3, 'ru', 'Horse', 'Лошадь'),
  (3, 'ru', 'Cow', 'Корова'),
  (3, 'zh', 'Dog', '狗'),
  (3, 'zh', 'Cat', '猫'),
  (3, 'zh', 'Bird', '鸟'),
  (3, 'zh', 'Fish', '鱼'),
  (3, 'zh', 'Horse', '马'),
  (3, 'zh', 'Cow', '牛'),
  (3, 'en', 'Perro', 'Dog'),
  (3, 'en', 'Gato', 'Cat'),
  (3, 'en', 'Pájaro', 'Bird'),
  (3, 'en', 'Pez', 'Fish'),
  (3, 'en', 'Caballo', 'Horse'),
  (3, 'en', 'Vaca', 'Cow'),
  (4, 'es', 'Shirt', 'Camisa'),
  (4, 'es', 'Shoes', 'Zapatos'),
  (4, 'es', 'Dress', 'Vestido'),
  (4, 'es', 'Hat', 'Sombrero'),
  (4, 'es', 'Coat', 'Abrigo'),
  (4, 'es', 'Pants', 'Pantalones'),
  (4, 'fr', 'Shirt', 'Chemise'),
  (4, 'fr', 'Shoes', 'Chaussures'),
  (4, 'fr', 'Dress', 'Robe'),
  (4, 'fr', 'Hat', 'Chapeau'),
  (4, 'fr', 'Coat', 'Manteau'),
  (4, 'fr', 'Pants', 'Pantalon'),
  (4, 'de', 'Shirt', 'Hemd'),
  (4, 'de', 'Shoes', 'Schuhe'),
  (4, 'de', 'Dress', 'Kleid'),
  (4, 'de', 'Hat', 'Hut'),
  (4, 'de', 'Coat', 'Mantel'),
  (4, 'de', 'Pants', 'Hose'),
  (4, 'it', 'Shirt', 'Camicia'),
  (4, 'it', 'Shoes', 'Scarpe'),
  (4, 'it', 'Dress', 'Vestito'),
  (4, 'it', 'Hat', 'Cappello'),
  (4, 'it', 'Coat', 'Cappotto'),
  (4, 'it', 'Pants', 'Pantaloni'),
  (4, 'pt', 'Shirt', 'Camisa'),
  (4, 'pt', 'Shoes', 'Sapatos'),
  (4, 'pt', 'Dress', 'Vestido'),
  (4, 'pt', 'Hat', 'Chapéu'),
  (4, 'pt', 'Coat', 'Casaco'),
  (4, 'pt', 'Pants', 'Calça'),
  (4, 'ru', 'Shirt', 'Рубашка'),
  (4, 'ru', 'Shoes', 'Обувь'),
  (4, 'ru', 'Dress', 'Платье'),
  (4, 'ru', 'Hat', 'Шляпа'),
  (4, 'ru', 'Coat', 'Пальто'),
  (4, 'ru', 'Pants', 'Брюки'),
  (4, 'zh', 'Shirt', '衬衫'),
  (4, 'zh', 'Shoes', '鞋子'),
  (4, 'zh', 'Dress', '连衣裙'),
  (4, 'zh', 'Hat', '帽子'),
  (4, 'zh', 'Coat', '大衣'),
  (4, 'zh', 'Pants', '裤子'),
  (4, 'en', 'Camisa', 'Shirt'),
  (4, 'en', 'Zapatos', 'Shoes'),
  (4, 'en', 'Vestido', 'Dress'),
  (4, 'en', 'Sombrero', 'Hat'),
  (4, 'en', 'Abrigo', 'Coat'),
  (4, 'en', 'Pantalones', 'Pants');
